contrib/cray/sft_test_results_baseline.txt

Add the capability to add intermittent test case errors to the sft_test_results_baseline.txt file.

contrib/cray: Add the capability to add intermittent errors to the baseline file.

---

contrib/cray/Jenkinsfile.verbs

SFT is failing due to a number of intermittent issues with verbs and SFT.
Allow the tests to pass until development can isolate the issue, and
continue to build libfabric normally via jenkins.

contrib/cray: Workaround for SFT test failures

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/fabtest_wrapper.sh

Wrap the fabtest script so it can be run client/server on any arbitrary set of nodes

contrib/cray: wrap fabtest script

---

contrib/cray/Jenkinsfile.verbs

Updating tests to use MPICH 3.3b3

contrib/cray: Migrate tests from MPICH 3.3b2 to 3.3b3

---

contrib/cray/bin/logwrap

In the logwrap script, the exit value of tee was being returned
rather than the status of the first command. This commit addresses
this issue by returning the pipestatus of command 0.

contrib/cray: Return exit value of test

---

prov/rxm/src/rxm.h

Do not merge. This is an optional PR that extracts an RXM bug fix required by the experimental XRC design from that PR.
The pad specified causes wasteful alignment. The Verbs experimental XRC implementation
uses some of the wasted space implementing sharing of XRC QP.

prov/rxm: Correct pad in RXM wire protocol structure

---

contrib/cray/Jenkinsfile.verbs

Groovy variables defined in the pipeline are not exported
as environment variables to 'sh' steps. This commit fixes
the existing problem in the pipeline by explicitly exporting
the LIBFABRIC_INSTALL variable as part of the LIBFABRIC_INSTALL_PATH
environment variable during the test stage.

contrib/cray: Address scoping error in Pipeline

---

configure.ac
prov/verbs/Makefile.include
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_rma.c

The initial implementation is intended to only support usage when accompanied
with the OFI RXM provider. The code must be configured using "--with-verbs-xrc"
and then explicitly enabled via the environment variables:
FI_OFI_RXM_USE_SRX=1, FI_VERBS_USE_XRC=1.
Both XRC INI and TGT QP are shared between message endpoints. XRC INI QP are
owned by the domain and shared between MSG endpoints within a process that
is sending to endpoints on the same remote node. XRC TGT QP are owned
by the linux kernel and are shared across processes by endpoints receiving
data from the endpoints within the same remote process.
Currently the RDMA CM is used for connection management setup only and
creates only the physical INI/TGT QP. Once connections are established,
the associated RDMA CM ID is destroyed. A …

prov/verbs: Initial experimental XRC EP_MSG implementation.

---

contrib/cray/bats/mpi.bats

To establish a good testing baseline, we need to skip some tests
for now. These tests will be enabled again in future commits.

contrib/cray: Establish testing baseline 

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/bin/run_libfabric_pipeline
contrib/cray/bin/verify_requirements.sh

It isn't very useful to have a 'latest' and 'stable'
is more of a 'nightly' validation rather than 'stable'.
This commit modifies the pipeline to reflect that.

contrib/cray: redefine stable to nightly tag

---

contrib/cray/Jenkinsfile.verbs

In a prior commit, a srun of ldd was left in accidently and was
not caught in review. This should be removed.

contrib/cray: remove unnecessary srun

---

contrib/cray/Jenkinsfile.verbs

Adds fi_ubertest to test matrix for Jenkins pipeline for
additional validation of the verbs provider.

contrib/cray: Add ubertest to test matrix

---

contrib/cray/Jenkinsfile.verbs

This commit introduces the isRelease function to the set of
criteria checked during the publish stage. If the branch name provided
is the same branch that should be published to the DST repository,
then the expression should trigger the publish stage.

contrib/cray: Change publish criteria

---

prov/rxm/src/rxm_cq.c

Add serialization around performing emulated atomic operations for an atomic request since a CQ lock is not held by default.

prov/rxm: Fix emulated atomics serialization.

---

prov/verbs/src/verbs_eq.c

This PR fixes two XRC CM REJ message handling bugs associated with CM REJ messages that are initiated from the CM, not the peer provider (two commits). It also temporarily disables the early release of XRC connection resources and lets the existing EP close normal processing handle it (one commit). The latter is to allow correct operation until resources remaining in timed wait state can be handled.

Fix segfault(s)/asserts in XRC handling of CM REJ messages

---

configure.ac
prov/util/src/util_atomic.c

Implements a version of emulated hardware atomics based on compiler built-in
memory model aware atomics. If not supported by the compiler, the handlers will
fall back to the previous version. Note: Only a subset of the atomic
op/data-type combinations are supported.

prov/util: Add support for common built-in memory model aware atomics

---

prov/rxm/src/rxm.h

When the underlying message endpoint is unable to connect, return -FI_EHOSTUNREACH instead of -FI_ENOTCONN, since the RDM EP itself is considered connectionless.

prov/rxm: Don't return ENOTCONN for RDM endpoint

---

man/fi_rxm.7.md

Explicitly note that in addition to the expected FI_EAGAIN error return cases as described in the fi_msg man page, that FI_EAGAIN error return should also be expected by the application during on-demand connection setup of the core provider message EP.
Application feedback has been that FI_EAGAIN was not expected on the first data transfer call.

prov/rxm: Add man page note for FI_EAGAIN during on-demand connection setup

---

prov/rxm/src/rxm_init.c

Make sure FI_MSG and FI_RMA caps are set correctly in the core provider
hints, taking into account FI_ATOMIC needs FI_MSG, and that FI_RMA and
FI_MSG may not both be set in info passed to an RXM EP.

prov/rxm: Fix setting of FI_MSG and FI_RMA caps for core hints

---

prov/rxm/src/rxm_init.c

Reverts SystemFabricWorks/libfabric#66

Revert "prov/rxm: Fix setting of FI_MSG and FI_RMA caps for core hints"

---

prov/rxm/src/rxm_cq.c

Do not access the CQ err_entry context prior to being initialized.

prov/rxm: Fix segfault reading provider CQ error entries.

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_domain.c

When returning the maximum atomic payload size reserve space for protocol headers.

prov/rxm: Fix initialization of maximum atomic payload size

---

prov/verbs/src/verbs_cm_xrc.c

If the physical INI XRC QP is rejected, allow any reciprocal INI
XRC QP connections pending on that QP to be scheduled.

prov/verbs: Fix shared XRC INI QP connection setup scheduling error

---

prov/rxm/src/rxm_cq.c

When setting the RXM CQ error entry status, convert provider
error to a positive code to comply with fi_cq_readerr
fi_cq_err_entry description.

prov/rxm: Fix setting of the CQ error entry "err" sign

---

prov/verbs/src/verbs_info.c

Handle the case where the application has not requested FI_RX_CQ_DATA
in the RX attribute check by removing FI_RX_CQ_DATA in a copy of the
default fi_info. Note, that this fix also removes the check of
domain->cq_data_size as a method of determining if FI_RX_CQ_DATA is
required. It is an error to set domain->cq_data_size and not also
include FI_RX_CQ_DATA.

prov/verbs: Make verbs fi_getinfo rx_attr verification thread-safe

---

prov/rxm/src/rxm.h

Correctly set the tx buffer descriptor when returning response with
fi_send.

prov/rxm: Fix sending of non-inline atomic response protocol message

---

prov/rxm/src/rxm_init.c

Clear EP max order size for unsupported message order and force
data FI_MANUAL_PROGRESS until auto data progress can be supported.

prov/rxm: Fix returned fi_info attributes when FI_ATOMIC is specified

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

Enable the RXM emulated FI_ATOMIC protocol to support one-sided
use cases where the target of the atomics is using data FI_PROGRESS_AUTO,
and is not calling into the API to make progress.
This progress will only be enabled if FI_ATOMIC is requested with data
FI_PROGRESS_AUTO and threading is either FI_THREAD_SAFE or FI_THREAD_UNSPEC.
It leverages the existing CM thread for this progress.

prov/rxm: Allow data FI_PROGRESS_AUTO with FI_ATOMIC capability

---

prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

Enable releasing of the H/W resources used to reserve unique QP numbers
during RDMA CM connection setup of XRC shared connections. Since the
RDMA CM is used for connection setup only, the associated RDMA CM ids
are disconnected and the QP that were reserved in the INIT state are
destroyed.

prov/verbs: Release XRC shared connection setup resources once connected

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_msg.c

Add MSG support for polling the CQ if needed on inject when threading model supports it. This mirrors what is done for RC.

prov/verbs: Add XRC support for inject_fast/injectdata_fast

---

prov/verbs/src/fi_verbs.c

XRC send side QP do not have responder logic, so avoid
attempting to set the minimum RNR NAK timer that should
be returned. It continues to be set for XRC receive QP.

prov/verbs: Do not update min RNR timer on XRC initiator QP

---

prov/rxm/src/rxm_conn.c

Peer ECONNREUSED errors are expected event, do not log
these as EQ error warnings.
When reading the MSG_EP EQ error the size returned from
fi_eq_readerr is checked. Although it should not happen, make
sure an error is returned if a mismatch in size is detected so
the contents of the error entry will not be used.

prov/rxm: MSG_EP rejects are expected, reduce logging severity

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_eq.c

When mapping connection tags to endpoints make the mapping to the
endpoint and the reset of the map entry a single protected operation.
Verify the mapped endpoint matches the requested key exactly. Make
sure to free connection tags for connections that do not complete
(e.g. rejected).

prov/verbs: Refactor/fixes for more robust XRC connection tag use

---

contrib/cray/bin/fabtest_wrapper.sh

If provided in the environment, use the fabtest installation in the environment.
This allows us to select the correct version of fabtests when running functional
tests.

contrib/cray: Use environment provided fabtests

---

prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_eq.c

Changes XRC logging to allow for selecting a logging level of warn
and a subsystem of ep_ctrl to capture both RXM and Verbs XRC
connection failure related logs.

prov/verbs: Align logging severity and subsystem for XRC with RXM

---

prov/rxm/src/rxm_cq.c

Add check to fix SRX use with OFIWG PR5123 fixes.

prov/rxm: Check for SRX use when freeing rx buf when msg_ep closed

---

prov/verbs/src/verbs_eq.c

When an RDMA CM disconnect event is received do not
immediately create a FI_SHUTDOWN event. Instead wait until
the timewait event is received before reporting the shutdown.
In larger fabrics we were seeing the FI_SHUTDOWN event delivered
prior to the QP fully draining and CQ entries processed.

prov/verbs: Fix shutdown notification for RC QP

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_eq.c

Add the capability to write an EQ entry while
already holding the EQ lock. This has not been seen in
practice, but could occur if an asynchronous call into
rdma_route_resolv() returned an error.

prov/verbs: Remove possible deadlock in XRC error path logic

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

This is a series of patches that implement using RDMA CM SIDR message exchanges to setup virtual/shared XRC QP connections. This avoids the necessity of creating temporary hardware resources when setting up the shared connections. With these changes XRC connection setup becomes faster than RC when the PPN count is greater than 4 PPN, and is up to 70% faster than the existing XRC connection setup implementation.

prov/verbs: Use RDMA CM SIDR message exchanges for shared XRC QP

---

man/fi_domain.3.md

Updated fi_domain man page with verbiage specifying system resources available at runtime may reduce the amount of EPs to less than what ep_cnt reports that an application is able to create
Signed-off-by: Leena Radeke <leena.radeke@hpe.com>

man/fi_domain: Available system resources may limit EP beyond ep_cnt

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/bats/batsgenerator.sh
contrib/cray/bats/benchmark.template
contrib/cray/bats/imb.bats

Included additional parameters constraining IMB tests to minimize amount of time test takes. Additionally extended applications timeout cutoff in Jenkinsfile.verbs file to avoid timeout failure.
Signed-off-by: Leena Radeke <leena.radeke@hpe.com>

contrib/cray: Update IMB parameters

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c

Reduce verbs provider message EP memory consumption by not duplicating and saving the fi_info passed. Instead extract only what is required from the fi_info. This results in a memory savings of about 750 bytes per verbs message endpoint, which can result in saving GBs of memory per node when utilizing all-to-all connectivity at a large scale.
Signed-off-by: Leena Radeke <leena.radeke@hpe.com>

prov/verbs:Reduce overall memory footprint in a fully connected fabric
